### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BadCo-NZ**
Added dependencies section

### CODE REVIEW

**Comment by CMiksche** [comment]
I am not sure if this section is needed. Normally python and pip are already installed on Linux systems, also this documentation only describes the installation on Debian based Linux systems (apt doesn't exists on e.g. Arch Linux).

To describe how to install pip shouldn't be part of this package (it is different for every Linux distro). This is just a pip package and users should be already familiar how to install pip packages before.

**Comment by BadCo-NZ** [comment]
> I am not sure if this section is needed. Normally python and pip are already installed on Linux systems, also this documentation only describes the installation on Debian based Linux systems (apt doesn't exists on e.g. Arch Linux).
> 
> To describe how to install pip shouldn't be part of this package (it is different for every Linux distro). This is just a pip package and users should be already familiar how to install pip packages before.

Well I would have to respectfully disagree :)

Currently I am using a Debian LXC for my Gitea instance (specifically [TKL](https://www.turnkeylinux.org/gitea)}, and it didn't come with the dependencies I mentioned. I am also a hobbyist homelabber and don't know much about python and pip packages.

How about if I change the dependency section to just say "ensure the following packages are installed..." instead of being Debian/Ubuntu specific?

**Comment by CMiksche** [comment]
> How about if I change the dependency section to just say "ensure the following packages are installed..." instead of being Debian/Ubuntu specific?

That would be fine by me

**Comment by BadCo-NZ** [comment]
Changed the wording, let me know what you think.

**Comment by CMiksche** [comment]
I merged it, thank you

**Pull request merged**
